### ISSUE TITLE
Chinese Text is garbled while put data into firebase.

### ISSUE THREAD

**Issue by zero123824** [bane73/firebase4j#11]
Hi ,

I'm a Chinese user,and find that Chinese words can't correctly put into my firebase.
In "Firebase.java" method "buildEntityFromJsonData" using **new StringEntity(jsonData).**
Is it properly useing **new StringEntity(jsonData, "utf-8")**  ?

Thank you.

**Comment by bane73** [comment]
Is this the same line you are looking at? https://github.com/bane73/firebase4j/blob/master/src/net/thegreshams/firebase4j/service/Firebase.java#L435

Looks like it is not using UTF-8.
You are welcome to send a pull-request and I will gladly accept it if the change solves your issue.

**Comment by bane73** [comment]
This issue is merged. Thank you @zero123824 for the pull-request.
