### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by omarathon** [bane73/firebase4j#15]
The URL for authentication is incorrect. The parameter is "access_token", not "auth", which is relevant to Firebase ID tokens, not OAuth2 access tokens. See: https://firebase.google.com/docs/database/rest/auth#section-using-the-access-token and https://stackoverflow.com/questions/44731746/firebase-could-not-parse-auth-token

**Comment by bane73** [comment]
Thanks @omarathon! Would you mind submitting a pull-request?

**Comment by chris7716** [comment]
Can we use this library for a Spring Boot application? If so, how can we do it?

**Comment by bane73** [comment]
Pull-request 17 merged: https://github.com/bane73/firebase4j/pull/17
