### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by chris7716** [bane73/firebase4j#18]
Can we use firebase4J with Spring Boot?

**Comment by bane73** [comment]
Yes I don't see any problems with that. This is really just a library, after all, should work in Boot no differently than any other library.

You'd just import into your pom.xml file [via Jitpack](https://jitpack.io/p/bane73/firebase4j) (make sure you refer to the 'Maven'-tab)... and then start coding it directly into your app wherever you'd like/need, as usual ([refer to my demo here](https://github.com/bane73/firebase4j/blob/master/src/net/thegreshams/firebase4j/demo/Demo.java) -- of course, you don't have to have it in a main() for it to work).

Now, depending on how familiar you already are with both Boot and also firebase4j, it would be my personal advice to not try to bite-off the entire enchilada at once. Instead, build a tiny main() of your own, in a Maven/pom.xml-based project, and just learn how to use firebase4j separately outside of Boot. Next, build a basic Boot hello-world app and just get familiar with Boot itself (be sure to use some other really simple library like StringUtils where you have to add a Maven-dependency to Boot for some external-project). ONLY THEN try to put the 2 together, once you are familiar with both. Just my $0.02.
