### ISSUE TITLE
query should be cleared instead of nulled in processResponse

### ISSUE THREAD

**Issue by attemptoHeinz** [bane73/firebase4j#19]
after successfully executing a request the query of the Firebase Object is nulled so that all addQuery calls after the first execution run into an NPE instead query.clear() should be used.

**Comment by bane73** [comment]
Hi @attemptoHeinz ! Appreciate the heads-up. If you would like to create a pull-request, I would be more than happy to sanity-review and merge.

**Comment by bane73** [comment]
Thanks.

https://github.com/bane73/firebase4j/pull/20
