### ISSUE TITLE
Correct Maven coordinates for Firebase4j

### ISSUE THREAD

**Issue by sagarrao** [bane73/firebase4j#4]
Hi, I was trying to use the firebase4j api for my gradle project. These are the maven co-ordinates that I specified:

compile('net.thegreshams:firebase4j:0.0.1-SNAPSHOT)' but I keep getting the error that this dependency can't be found.. Just wanted to know is it available on the public maven repo or somewhere else?

**Comment by bane73** [comment]
No, I'm sorry but it's not actually available in a repo anywhere.  There really hasn't been enough usage to warrant it.  You'll have to download it and install it locally I'm afraid.

**Comment by KaidenR** [comment]
I was looking into using your library with Maven as well. Your usage numbers would be higher if you did have it on Maven =) It would be much easier for people to consume.

**Comment by sagarrao** [comment]
@KaidenR Actually, you can use the firebase-client apis.. That's exactly what I used evetually, and yeah in a way, the apis have moved on from what we had here...

**Comment by KaidenR** [comment]
@sagarrao I tried using the firebase-client and it won't work for me because it spawns new threads which is not allowed in the environment I'm using. I'm using this one because it does simple Http requests over the REST API.

**Comment by bane73** [comment]
Are you guys suggesting there is still a need for this wrapper?  To be honest, I have not followed the Firebase project since it's early beta days because the projects I work on really do not lend to it and I've just been busy pursuing other things.

But if there's still a need for this, I might be interested in evolving it.  Aside from being in the public Maven repo, is there anything else important this library should have added to it?

**Comment by KaidenR** [comment]
The Firebase documentation has your repo listed as the only suggested library for interacting with the Firebase REST API via Java:
https://www.firebase.com/docs/rest/quickstart.html

I'd say that alone is reason enough to keep this project alive =)

But I also want to see it kept alive for my own selfish use too.

**Comment by bane73** [comment]
Just in case this left you hanging, I failed to update with what I did to resolve this via jitpack but if you check out this link you can bring in via Maven via Jitpack:
https://jitpack.io/p/bane73/firebase4j
