### ISSUE TITLE
unable to convert data from map into json

### ISSUE THREAD

**Issue by reesque** [bane73/firebase4j#8]
Idk why but I followed the demo and this pops up. Any idea how to fix it?

**Comment by bane73** [comment]
Apologies, @leScepter somehow I failed to notice this issue until just now. :\
Anyways, if it remains an issue and you are still interested in exploring it I might have more time now: feel free to create a demo-app in GH and send me a ref and I'll see if I can spot an issue in your impl. Quite a few people have been using it this last year so I'm assuming the project still works.
